name: Hello orbit

on:
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Targer ARC name used for `runs-on`in job'
        default: oziel-predev-runner-01
        required: false

jobs:
  arc-runner-job:
    runs-on: ${{ inputs.arc_name }}
    container: busybox
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello Orbit
        run: |
          echo "Hello, Orbit!!"
          sleep 360
