name: Hello orbit

on:
  workflow_dispatch:
    inputs:
      arc_name:
        description: 'Targer ARC name used for `runs-on`in job'
        default: k8s-runner
        required: false

jobs:
  arc-runner-job:
    runs-on: ${{ inputs.arc_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello Orbit
        run: |
          echo "Hello, Orbit!!"
          helm list -A
